const types = {
  ADD_BREAD: "ADD_BREAD",
  REMOVE_BREAD: "REMOVE_BREAD",
  ADD_MEAT: "ADD_MEAT",
  REMOVE_MEAT: "REMOVE_MEAT",
  ADD_CHEESE: "ADD_CHEESE",
  REMOVE_CHEESE: "REMOVE_CHEESE",
  ADD_SALAD: "ADD_SALAD",
  REMOVE_SALAD: "REMOVE_SALAD",
};

export default types;
